apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::879559838728:role/eksctl-eksctl-demo-new-nodegroup-NodeInstanceRole-1VF6DDQSSRA6X
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::879559838728:role/UdacityFlaskDeployCBKubestlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-15T20:42:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1395"
  uid: 481f3edc-3eb4-4e2f-845c-c83ab824eb7d
